---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
# https://gethomepage.dev/configs/services/

- Media:
    - Jellyfin:
        href: http://10.0.0.208:8096
        description: Watch.
        icon: jellyfin
    - Navidrome:
        href: http://10.0.0.208:4533
        description: Listen.
        icon: music
    - Jellyseerr:
        href: http://10.0.0.208:5055
        description: Discover.
        icon: jellyseerr

- Cloud:
    - Nextcloud:
        href: http://10.0.0.157:80
        description: Gather.
        icon: cloud
    - Homepage:
        href: http://10.0.0.208:3000
        description: Dashboard.
        icon: home

